### ISSUE TITLE
version 1

### ISSUE THREAD

**Issue by aliefprihantoro** [muryp/sosmed-management.js#1]
### Goal

- user can upload video
- user can upload foto
- user can schedule upload

### Produk Description

one click for upload in multi social media.

### Who's it for?
- for content creator

### Why build it?
- for easy upload

### Assumption

- maybe user have different format video
- maybe user have different resolution of video

### Future ISSUE

- [ ] feat(auth): signin page
- [ ] feat(auth): signup page
- [ ] feat(list): content(status)
- [ ] feat(upload): form and file input
- [ ] feat(settings): form settings and checkbox
- [ ] feat(auth): integrate supabase login
- [ ] feat(upload): integration supabase upload file
- [ ] feat(list): integrate with db/backend
- [ ] feat(cronjob): upload if on date released
- [ ] test(login): e2e test
- [ ] ci: deploy
- [ ] deploy

### Milestone

- [sprint 1 (m1)](https://github.com/muryp/sosmed-management.js/milestone/1)

### Desain

- color :
- font

### Teknologi

- **Astro js** (full stack framework)
- **Typescript** (types checking).
- **supabase** for (auth and db)

### Code Quiality

- user only upload images/video/text
- user can upload if login
